#!/usr/bin/env bash

base_dir="$HOME/brain/"
note_selection=$(printf "New\n%s" "$(find "$base_dir" -type f -name "*.md" -printf "%P\n")" | rofi -dmenu)

if [[ "$note_selection" == "New" ]]; then
  new_note_name=$(echo "" | rofi -dmenu -p "New note name:")
  if [[ -z "$new_note_name" ]]; then
    note=$(date +"%Y-%m-%d").md
  else
    note=$(echo "$new_note_name.md" | tr ' ' '_')
  fi
else
  note="$note_selection"
fi

if [[ -n "$note" ]]; then
  if tmux has-session 2>/dev/null; then
    # Open the file in a new tmux window and immediately select it
    tmux new-window -n "quicknote" "nvim '$base_dir$note'"
  else
    # If no tmux session is found, open a new alacritty window
    alacritty --title "quicknote" -e nvim "$base_dir$note"
  fi
  # tmux display-popup -E "nvim $base_dir$note"
fi
