#!/usr/bin/env bash

# Get a list of available wifi connections and morph it into a nice-looking list
wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list |
  sed 1d |
  sed -E '
    s/  */ /g;
    s/WPA*.?\S/ /g;
    s/^--/ /g;
    s/  //g;
    /--/d
  '
)

# Detect Wi-Fi state and set default menu options
if nmcli radio wifi | grep -q "enabled"; then
  default_options="󰖪  Disable Wi-Fi\n Rescan Wi-Fi"
else
  default_options="󰖩  Enable Wi-Fi"
fi

# Use rofi to select wifi network
chosen_network=$(echo -e "$default_options${wifi_list:+\n$wifi_list}" |
  uniq -u |
  rofi -dmenu -i -selected-row 1 -p "Wi-Fi SSID: "
)

# Get name of connection
#read -r chosen_id <<< "${chosen_network:3}"
chosen_id="${chosen_network:3}"

if [ "$chosen_network" = "" ]; then
	exit
elif [ "$chosen_network" = "󰖩  Enable Wi-Fi" ]; then
	nmcli radio wifi on
  exec "$0"
elif [ "$chosen_network" = " Rescan Wi-Fi" ]; then
	nmcli device wifi rescan
  notify-send "Scanning for Wi-Fi networks..."
  sleep 2
  exec "$0"
elif [ "$chosen_network" = "󰖪  Disable Wi-Fi" ]; then
	nmcli radio wifi off
  exec "$0"
else
	# Message to show when connection is activated successfully
  success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
  
  # Check if it's a saved network (password is saved)
  if nmcli -g NAME connection | grep -Fxq "$chosen_id"; then
		nmcli connection up id "$chosen_id" | grep "successfully" &&
      notify-send "Connection Established" "$success_message"
	else
		if [[ "$chosen_network" =~ "" ]]; then
			wifi_password=$(rofi -dmenu -password -p "Password: " )
		fi
		nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" &&
      notify-send "Connection Established" "$success_message"
    fi
fi
