#!/usr/bin/env bash

GATEWAY="10.0.0.1"
INTERFACE="wg0"

# This command checks for a recent handshake and pings the gateway.
if ping -c 1 "$GATEWAY" -I "$INTERFACE" > /dev/null 2>&1; then
  printf '{"text": " VPN", "tooltip": "VPN Connected", "class": "connected"}'
fi
