#!/bin/sh
# Check for the "latest handshake" string in the output of `wg show`.
if sudo /run/current-system/sw/bin/wg show | grep -q "latest handshake"; then
# Print JSON for Waybar if connected.
printf '{"text": " VPN", "tooltip": "VPN Connected", "class": "connected"}'
fi
