#!/bin/bash
SESSION="brain_session"
FILE="$HOME/brain"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux new-session -d -s "$SESSION" "nvim $FILE"
fi

tmux popup -xC -yC -w 80% -h 80% "tmux attach-session -t $SESSION"
