#!/usr/bin/env bash

# Perform fuzzy search for passwords in GoPass
selected_password=$(gopass ls --flat | fzf --prompt="Search Password: ")

# If a password is selected, copu its content to the clipboard
if [ -n "$selected_password" ]; then
  password=$(gopass show "$selected_password")
  echo -n "$password" | xclip -selection clipboard
fi
