#!/usr/bin/env bash

if ! pgrep -x 1Password > /dev/null; then
  1password --silent > /dev/null 2>&1 &
fi

item=$(op item list --format=json | jq -r '.[].title' | fzf)

if [[ -n "$item" ]]; then
  password=$(op item get "$item" --fields password --reveal)
    echo -n "$password" | xclip -selection clipboard
fi
